title: SMART Absen SMA UII
description: Dokumentasi teknis lengkap — sistem presensi digital terintegrasi SMA UII Yogyakarta
theme: jekyll-theme-cayman
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/SMA-UII-Yogyakarta/aksesekolah
